JEESample/JEESample-war/src/java/co/com/jee/sample/mb/TablaParametroController.java
package co.com.jee.sample.mb;

import co.com.jee.sample.ejb.TablaParametroFacade;
import co.com.jee.sample.entity.TablaParametro;
import co.com.jee.sample.mb.util.JsfUtil;
import co.com.jee.sample.mb.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("tablaParametroController")
@SessionScoped
public class TablaParametroController implements Serializable {

    private TablaParametro current;
    private DataModel items = null;
    @EJB
    private TablaParametroFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TablaParametroController() {
    }

    public TablaParametro getSelected() {
        if (current == null) {
            current = new TablaParametro();
            selectedItemIndex = -1;
        }
        return current;
    }

    private TablaParametroFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (TablaParametro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new TablaParametro();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TablaParametroCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (TablaParametro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TablaParametroUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (TablaParametro) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TablaParametroDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public TablaParametro getTablaParametro(java.math.BigDecimal id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = TablaParametro.class)
    public static class TablaParametroControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TablaParametroController controller = (TablaParametroController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "tablaParametroController");
            return controller.getTablaParametro(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof TablaParametro) {
                TablaParametro o = (TablaParametro) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + TablaParametro.class.getName());
            }
        }

    }

}

JEESample/JEESample-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="welcomePrimefaces" value="Primefaces welcome page" />
        <br />
        <h:link outcome="/tablaParametro/List" value="Show All TablaParametro Items"/>
    </h:body>

</html>

JEESample/JEESample-war/web/tablaParametro/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateTablaParametroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateTablaParametroLabel_id}" for="id" />
                    <h:inputText id="id" value="#{tablaParametroController.selected.id}" title="#{bundle.CreateTablaParametroTitle_id}" required="true" requiredMessage="#{bundle.CreateTablaParametroRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateTablaParametroLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{tablaParametroController.selected.nombre}" title="#{bundle.CreateTablaParametroTitle_nombre}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{tablaParametroController.create}" value="#{bundle.CreateTablaParametroSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{tablaParametroController.prepareList}" value="#{bundle.CreateTablaParametroShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateTablaParametroIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JEESample/JEESample-war/web/tablaParametro/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditTablaParametroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditTablaParametroLabel_id}" for="id" />
                    <h:inputText id="id" value="#{tablaParametroController.selected.id}" title="#{bundle.EditTablaParametroTitle_id}" required="true" requiredMessage="#{bundle.EditTablaParametroRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditTablaParametroLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{tablaParametroController.selected.nombre}" title="#{bundle.EditTablaParametroTitle_nombre}" />
                </h:panelGrid>
                <h:commandLink action="#{tablaParametroController.update}" value="#{bundle.EditTablaParametroSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditTablaParametroViewLink}"/>
                <br />
                <h:commandLink action="#{tablaParametroController.prepareList}" value="#{bundle.EditTablaParametroShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditTablaParametroIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JEESample/JEESample-war/web/tablaParametro/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTablaParametroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListTablaParametroEmpty}" rendered="#{tablaParametroController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{tablaParametroController.items.rowCount > 0}">
                    <h:outputText value="#{tablaParametroController.pagination.pageFirstItem + 1}..#{tablaParametroController.pagination.pageLastItem + 1}/#{tablaParametroController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{tablaParametroController.previous}" value="#{bundle.Previous} #{tablaParametroController.pagination.pageSize}" rendered="#{tablaParametroController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{tablaParametroController.next}" value="#{bundle.Next} #{tablaParametroController.pagination.pageSize}" rendered="#{tablaParametroController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{tablaParametroController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTablaParametroTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTablaParametroTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{tablaParametroController.prepareView}" value="#{bundle.ListTablaParametroViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tablaParametroController.prepareEdit}" value="#{bundle.ListTablaParametroEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tablaParametroController.destroy}" value="#{bundle.ListTablaParametroDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{tablaParametroController.prepareCreate}" value="#{bundle.ListTablaParametroCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTablaParametroIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JEESample/JEESample-war/web/tablaParametro/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewTablaParametroTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewTablaParametroLabel_id}"/>
                    <h:outputText value="#{tablaParametroController.selected.id}" title="#{bundle.ViewTablaParametroTitle_id}"/>
                    <h:outputText value="#{bundle.ViewTablaParametroLabel_nombre}"/>
                    <h:outputText value="#{tablaParametroController.selected.nombre}" title="#{bundle.ViewTablaParametroTitle_nombre}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{tablaParametroController.destroyAndView}" value="#{bundle.ViewTablaParametroDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewTablaParametroEditLink}"/>
                <br />
                <h:commandLink action="#{tablaParametroController.prepareCreate}" value="#{bundle.ViewTablaParametroCreateLink}" />
                <br />
                <h:commandLink action="#{tablaParametroController.prepareList}" value="#{bundle.ViewTablaParametroShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewTablaParametroIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

JEESample/JEESample-war/web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>

JEESample/JEESample-war/web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>